### ISSUE TITLE
Black debug panes on launch

### ISSUE THREAD

**Issue by onefifth** [robinvierich/SublimeTextGRLD#1]
**Issue**
When reopening a saved workspace, tabs and panes created by the debugger plugin will restore incorrectly, often showing up as pure black. 

**Fix:**
We need to properly restore the plugin controlled panes/groups when Sublime loads a saved workspace that includes panes containing debugger content.

**Less ideal fixes:**
- Omit these panes/groups from the workspace serialization
- Close these panes when they are first restored by sublime (recreating them on manual debugger connect)

I think both of these options don't really follow the sublime ideology of restoring the layout to a state that matches the last used one. We should strive to serialize/restore these panes as best as possible, even if the contents are empty or display some kind of "debugger disconnected" message.

**Comment by robinvierich** [comment]
Should be fixed in this commit: fcdc6b573f80d9caccde3b603051c567e648e039
